/**
 * Zero-dependency token build: DTCG JSON -> generated CSS partials + typed
 * token-data module + flat JSON. Adapted from the old @vanduo-oss/core
 * scripts/build.mjs and the framework-partial emission of its
 * generate-fib-palette.mjs — vd3 owns both halves now.
 *
 * Outputs:
 *   css/core/generated/colors-fib-base.css  raw --vd-oc-* / --vd-fib-* scales
 *   css/core/generated/colors-palette.css   active --vd-* layer + [data-palette] switch
 *   dist/tokens.js                          ESM: customizer arrays, DEFAULTS, resolved `tokens` map
 *   dist/tokens.d.ts                        precise types for the above
 *   dist/tokens.json                        flat { "--vd-name": literal } + customizer (Figma-ready)
 *
 * Runs first in the build chain (after clean-dist), before build-css and
 * vite — see openspec/changes/vd3-token-css-foundation/design.md.
 * Deterministic: byte-identical output across runs.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const tokensDir = resolve(root, "tokens");
const distDir = resolve(root, "dist");
const generatedDir = resolve(root, "css", "core", "generated");

// Deterministic emit order: scale + semantics share the generic pipeline; the
// two color palettes (Open Color + Fibonacci) are emitted as namespaced raw
// scales plus an active layer with a runtime [data-palette] switch.
const TOKEN_FILES = [
  "primitive/scale.tokens.json",
  "semantic/color.tokens.json",
];
const OC_COLOR_FILE = "primitive/color.tokens.json";
const FIB_COLOR_FILE = "primitive/color.fib.tokens.json";

const readJson = (rel) =>
  JSON.parse(readFileSync(resolve(tokensDir, rel), "utf8"));

/** `{a.b.c}` -> `--vd-a-b-c` (segments split on dot, dashes within a segment kept). */
const refToVar = (ref) => "--vd-" + ref.slice(1, -1).replace(/\./g, "-");
const isRef = (value) => typeof value === "string" && /^\{[^}]+\}$/.test(value);

/** Walk a DTCG tree, emitting { name, raw, type } in document order. */
const flatten = (node, path, out) => {
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    if (child && typeof child === "object" && "$value" in child) {
      out.push({
        name: "--vd-" + [...path, key].join("-"),
        raw: String(child.$value),
        type: child.$type ?? "other",
      });
    } else if (child && typeof child === "object") {
      flatten(child, [...path, key], out);
    }
  }
};

// Generic (non-color-palette) tokens: scale + semantic, references kept as var().
const allTokens = [];
for (const file of TOKEN_FILES) flatten(readJson(file), [], allTokens);

// Palette primitives: keep references resolvable within each palette namespace.
const ocColors = [];
flatten(readJson(OC_COLOR_FILE), [], ocColors);
const fibColors = [];
flatten(readJson(FIB_COLOR_FILE), [], fibColors);

// `--vd-red` -> `red-0` style suffix (drops the `--vd-` prefix).
const suffix = (name) => name.slice("--vd-".length);
// Resolve Open Color internal refs ({danger.0}) to literal hex so the namespaced
// --vd-oc-* scale matches the old framework's literal base partial (parity).
const ocRawByName = new Map(ocColors.map((t) => [t.name, t.raw]));
const resolveLiteral = (raw, seen = new Set()) => {
  if (!isRef(raw)) return raw;
  const name = refToVar(raw);
  if (seen.has(name)) return raw;
  seen.add(name);
  const next = ocRawByName.get(name);
  return next === undefined ? raw : resolveLiteral(next, seen);
};

// Families that exist in Open Color -> switchable between palettes. The golden
// accent track is Fibonacci-only (no Open Color counterpart).
const ocSuffixes = ocColors.map((t) => suffix(t.name));
const ocSuffixSet = new Set(ocSuffixes);
const fibSuffixes = fibColors.map((t) => suffix(t.name));

// ── CSS partial 1: raw namespaced scales (literal hex). Rule body must stay
// byte-identical to the old framework/css/core/colors-fib-base.css. ──
const ocLines = ocColors.map(
  (t) => `  --vd-oc-${suffix(t.name)}: ${resolveLiteral(t.raw)};`,
);
const fibLines = fibColors.map(
  (t) => `  --vd-fib-${suffix(t.name)}: ${t.raw};`,
);
const fibBaseCss =
  "/**\n * Vanduo vd3 - Palette Base Scales (generated)\n" +
  " *\n" +
  " * Raw, palette-namespaced color scales for the runtime [data-palette] switch.\n" +
  " *   --vd-oc-*  Open Color (optional palette)\n" +
  " *   --vd-fib-* Fibonacci / golden-angle (optional palette) + golden accent track\n" +
  " *\n" +
  " * Generated by @vanduo-oss/vd3 scripts/build-tokens.mjs from tokens/*.tokens.json.\n" +
  " * Do not edit by hand; run `pnpm build:tokens`.\n" +
  " */\n\n" +
  ":root {\n" +
  "  /* Open Color palette (optional) */\n" +
  ocLines.join("\n") +
  "\n\n  /* Fibonacci (golden-angle) palette (default) + golden accent track */\n" +
  fibLines.join("\n") +
  "\n}\n";

// ── CSS partial 2: active layer + runtime switch. Imported AFTER colors.css so
// the active scales override the legacy literals. Rule body must stay
// byte-identical to the old framework/css/core/colors-palette.css. ──
const activeLines = fibSuffixes.map((s) =>
  ocSuffixSet.has(s)
    ? `  --vd-${s}: var(--vd-oc-${s});`
    : `  --vd-${s}: var(--vd-fib-${s});`,
);
const switchBlock = (palette, prefix, suffixes) =>
  `[data-palette="${palette}"] {\n` +
  suffixes.map((s) => `  --vd-${s}: var(--vd-${prefix}-${s});`).join("\n") +
  "\n}\n";
const paletteCss =
  "/**\n * Vanduo vd3 - Active Palette Layer (generated)\n" +
  " *\n" +
  " * Binds the active --vd-<family>-<step> scales to a palette and provides the\n" +
  " * [data-palette] runtime switch. Open Color is the default;\n" +
  ' * [data-palette="fibonacci"] opts into the Fibonacci (golden-angle) palette.\n' +
  " *\n" +
  " * Generated by @vanduo-oss/vd3 scripts/build-tokens.mjs. Do not edit by hand;\n" +
  " * run `pnpm build:tokens`. Import AFTER colors.css.\n" +
  " */\n\n" +
  ":root {\n" +
  "  /* Active scales default to the Open Color palette */\n" +
  activeLines.join("\n") +
  "\n}\n\n" +
  switchBlock("fibonacci", "fib", fibSuffixes) +
  "\n" +
  switchBlock("open-color", "oc", ocSuffixes);

// ── Resolved literal map (for tokens.json / tokens.js). ──
// Active scales reflect the DEFAULT palette (Open Color) for shared families;
// the Fibonacci-only golden accent track resolves to its Fibonacci literals.
const fibLiteralBySuffix = new Map(
  fibColors.map((t) => [suffix(t.name), t.raw]),
);
const ocLiteralBySuffix = new Map(
  ocColors.map((t) => [suffix(t.name), resolveLiteral(t.raw)]),
);
const rawByName = new Map();
for (const t of ocColors)
  rawByName.set(`--vd-oc-${suffix(t.name)}`, resolveLiteral(t.raw));
for (const t of fibColors) rawByName.set(`--vd-fib-${suffix(t.name)}`, t.raw);
for (const s of fibSuffixes)
  rawByName.set(
    `--vd-${s}`,
    ocSuffixSet.has(s) ? ocLiteralBySuffix.get(s) : fibLiteralBySuffix.get(s),
  );
for (const t of allTokens) rawByName.set(t.name, t.raw);

const resolveAny = (raw, seen = new Set()) => {
  if (!isRef(raw)) return raw;
  const name = refToVar(raw);
  if (seen.has(name)) return raw; // cycle guard
  seen.add(name);
  const next = rawByName.get(name);
  return next === undefined ? raw : resolveAny(next, seen);
};

const emittedNames = [
  ...ocColors.map((t) => `--vd-oc-${suffix(t.name)}`),
  ...fibColors.map((t) => `--vd-fib-${suffix(t.name)}`),
  ...fibSuffixes.map((s) => `--vd-${s}`),
  ...allTokens.map((t) => t.name),
];
const resolvedTokens = Object.fromEntries(
  emittedNames.map((n) => [n, resolveAny(rawByName.get(n))]),
);

// ── Customizer option metadata. ──
const opts = readJson("customizer/options.json");
const DEFAULTS = {
  PALETTE: opts.defaults.palette,
  PRIMARY_LIGHT: opts.defaults.primaryLight,
  PRIMARY_DARK: opts.defaults.primaryDark,
  NEUTRAL: opts.defaults.neutral,
  RADIUS: opts.defaults.radius,
  FONT: opts.defaults.font,
  THEME: opts.defaults.theme,
};
const union = (values) => values.map((v) => JSON.stringify(v)).join(" | ");
const paletteKeys = opts.palettes.map((p) => p.key);

// ── tokens.js (ESM data — same export surface as the old @vanduo-oss/core). ──
const tokensJs =
  "// Generated by @vanduo-oss/vd3 scripts/build-tokens.mjs — do not edit by hand.\n" +
  `export const PALETTE_OPTIONS = ${JSON.stringify(opts.palettes, null, 2)};\n\n` +
  `export const PRIMARY_COLORS = ${JSON.stringify(opts.primary, null, 2)};\n\n` +
  `export const NEUTRAL_COLORS = ${JSON.stringify(opts.neutral, null, 2)};\n\n` +
  `export const RADIUS_OPTIONS = ${JSON.stringify(opts.radius)};\n\n` +
  `export const FONT_OPTIONS = ${JSON.stringify(opts.fonts, null, 2)};\n\n` +
  `export const THEME_MODES = ${JSON.stringify(opts.themeModes)};\n\n` +
  `export const DEFAULTS = ${JSON.stringify(DEFAULTS, null, 2)};\n\n` +
  `export const tokens = ${JSON.stringify(resolvedTokens, null, 2)};\n`;

// ── tokens.d.ts (precise types). ──
const tokensDts =
  "// Generated by @vanduo-oss/vd3 scripts/build-tokens.mjs — do not edit by hand.\n" +
  "export interface ColorDef { readonly key: string; readonly name: string; readonly color: string; }\n" +
  "export interface FontDef { readonly key: string; readonly name: string; }\n" +
  "export interface PaletteDef { readonly key: string; readonly name: string; readonly description: string; }\n" +
  `export type RadiusOption = ${union(opts.radius)};\n` +
  `export type ThemeMode = ${union(opts.themeModes)};\n` +
  `export type Palette = ${union(paletteKeys)};\n` +
  "export interface ThemeDefaults {\n" +
  "  readonly PALETTE: Palette;\n  readonly PRIMARY_LIGHT: string;\n  readonly PRIMARY_DARK: string;\n" +
  "  readonly NEUTRAL: string;\n  readonly RADIUS: RadiusOption;\n" +
  "  readonly FONT: string;\n  readonly THEME: ThemeMode;\n}\n" +
  "export declare const PALETTE_OPTIONS: readonly PaletteDef[];\n" +
  "export declare const PRIMARY_COLORS: readonly ColorDef[];\n" +
  "export declare const NEUTRAL_COLORS: readonly ColorDef[];\n" +
  "export declare const RADIUS_OPTIONS: readonly RadiusOption[];\n" +
  "export declare const FONT_OPTIONS: readonly FontDef[];\n" +
  "export declare const THEME_MODES: readonly ThemeMode[];\n" +
  "export declare const DEFAULTS: ThemeDefaults;\n" +
  "export declare const tokens: Readonly<Record<string, string>>;\n";

// ── tokens.json (flat, resolved + customizer — old core/dist/tokens.json shape). ──
const tokensJson = {
  $description:
    "Vanduo design tokens — resolved CSS custom properties + customizer options.",
  cssVariables: resolvedTokens,
  customizer: { ...opts },
};
delete tokensJson.customizer.$description;

mkdirSync(distDir, { recursive: true });
mkdirSync(generatedDir, { recursive: true });
writeFileSync(resolve(generatedDir, "colors-fib-base.css"), fibBaseCss);
writeFileSync(resolve(generatedDir, "colors-palette.css"), paletteCss);
writeFileSync(resolve(distDir, "tokens.js"), tokensJs);
writeFileSync(resolve(distDir, "tokens.d.ts"), tokensDts);
writeFileSync(
  resolve(distDir, "tokens.json"),
  JSON.stringify(tokensJson, null, 2) + "\n",
);

console.log(
  `Built ${emittedNames.length} tokens -> css/core/generated/{colors-fib-base,colors-palette}.css + dist/{tokens.js, tokens.d.ts, tokens.json}\n` +
    `Palettes: ${paletteKeys.join(", ")} (default ${DEFAULTS.PALETTE})\n` +
    `Customizer: ${opts.primary.length} primary, ${opts.neutral.length} neutral, ` +
    `${opts.radius.length} radius, ${opts.fonts.length} fonts`,
);
